sudo: required
services:
  - docker

before_installl:
  - docker build -t saulomontenegro/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true saulomontenegro/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-560383962045"
  bucket_path: "docker-react"
  on:
      btanch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY